name: Testing the Python code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./N1/requirements.txt ]; then pip install -r ./N1/requirements.txt; fi
   
    - name: Lint with pycodestyle
      run: |
        pycodestyle ./N1/src ./N1/test
    
    - name: Test with pytest
      run: |
        PYTHONPATH=./N1:./N1/src/ pytest test